//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace SharpCommunication.Base.Codec.Commands.Records.CodeBook
{
// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://tempuri.org/CodeBookSchema.xsd")]
    [XmlRoot(Namespace="http://tempuri.org/CodeBookSchema.xsd", IsNullable=false)]
    public partial class PropertyCodeBook {
    
        private string versionField;
    
        private Property[] propertiesField;
    
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("Properties")]
        public Property[] Properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://tempuri.org/CodeBookSchema.xsd")]
    public partial class Property {
    
        private string nameField;
    
        private PropertyFormat formatField;
    
        private int sizeField;
    
        private string descriptionField;
    
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    
        /// <remarks/>
        public PropertyFormat Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
    
        /// <remarks/>
        public int Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
    
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://tempuri.org/CodeBookSchema.xsd")]
    public enum PropertyFormat {
    
        /// <remarks/>
        Number,
    
        /// <remarks/>
        Buffer,
    }
}